# Generated by Django 5.2.8 on 2025-11-06 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bombero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('rol', models.CharField(choices=[('Bombero', 'Bombero'), ('Jefe de Guardia', 'Jefe de Guardia'), ('Admin', 'Administrador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipercode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código VIPER')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de Emergencia (Clave)')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asistentes', models.ManyToManyField(related_name='emergencias_atendidas', to='gestion.bombero')),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la guardia')),
                ('tipo', models.CharField(default='Nocturna', max_length=20, verbose_name='Tipo de Guardia')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('bombero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias', to='gestion.bombero')),
            ],
        ),
    ]
