# Generated by Django 4.2.4 on 2025-11-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='apoyo_externo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apoyo externo (Carabineros/SAMU/otros)'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='herramientas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Herramientas utilizadas'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar o sector'),
        ),
    ]
