# Generated by Django 4.2.26 on 2025-11-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_guardia_apoyo_externo_guardia_herramientas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencia',
            name='apoyo_externo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apoyo externo (Carabineros/SAMU/otros)'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='herramientas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Herramientas utilizadas'),
        ),
        migrations.AddField(
            model_name='emergencia',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar o sector'),
        ),
    ]
