# Generated by Django 4.2.4 on 2025-11-21 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_emergencia_apoyo_externo_emergencia_herramientas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=50)),
                ('llegada', models.DateTimeField(blank=True, null=True)),
                ('retiro', models.DateTimeField(blank=True, null=True)),
                ('llegada_cuartel', models.DateTimeField(blank=True, null=True)),
                ('guardia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='gestion.guardia')),
            ],
        ),
    ]
