# Generated by Django 5.2.8 on 2025-11-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_materialmayor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencia',
            options={'verbose_name_plural': 'Emergencias'},
        ),
        migrations.AddField(
            model_name='emergencia',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Registro Manual'), ('VIPER', 'Sincronizado desde VIPER')], default='MANUAL', max_length=20, verbose_name='Origen de la emergencia'),
        ),
    ]
